# Generated by Django 3.0.6 on 2020-06-01 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisedata',
            name='image',
            field=models.ImageField(default='exercise.jpg', upload_to='exercise_pics'),
        ),
        migrations.AlterField(
            model_name='exercisedata',
            name='workout_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_data', to='workouts.WorkoutData'),
        ),
    ]
