# Generated by Django 3.0.6 on 2020-06-02 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_auto_20200531_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='weight_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
