# Generated by Django 3.0.6 on 2020-06-06 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_auto_20200606_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='code',
            field=models.IntegerField(default=0, verbose_name='Code'),
        ),
        migrations.AlterUniqueTogether(
            name='weight',
            unique_together={('exercise', 'code')},
        ),
    ]
